### ISSUE TITLE
MediaQueries

### ISSUE THREAD

**Issue by Tinnni** [SJarno/SantaService#7]
- [x] Make sure that sizing
- [x] All mobile views - presets sizes properly on all pages
- [x] All other views sizes properly on all pages - big screen etc

**Comment by SJarno** [comment]
Tämä saattaa olla hieman isompi juttu, pitänee varmistaa mobiilin lisäksi se, että skaalautuu myös isommilla näytöillä oikein.

Mobiilit ensin?

**Comment by SJarno** [comment]
Lisätty nyt reilusti media quereja sivun vähimmäiskokoon liittyen sekä asettelua flexboksilla lomakkeisiin liittyen.

**Comment by SJarno** [comment]
Pääasiassa hoidettu, mutta toki lisää elementtejä kun on tullut/tulee, niin pitää tsekkailla myöhemmin.
